/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Handle navigation requests - ALWAYS use network first for HTML pages
// This prevents the offline page from being cached
registerRoute(
    ({ request }) => request.mode === 'navigate',
    new NetworkFirst({
        cacheName: 'pages-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
        networkTimeoutSeconds: 3,
    })
);

// Cache Google Fonts
registerRoute(
    /^https:\/\/fonts\.googleapis\.com\/.*/i,
    new CacheFirst({
        cacheName: 'google-fonts-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
            }),
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
);

// Cache Google Fonts static resources
registerRoute(
    /^https:\/\/fonts\.gstatic\.com\/.*/i,
    new CacheFirst({
        cacheName: 'gstatic-fonts-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
            }),
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
);

// Cache Supabase API with NetworkFirst
registerRoute(
    /^https:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
    new NetworkFirst({
        cacheName: 'supabase-api-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 60 * 5, // 5 minutes
            }),
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
        networkTimeoutSeconds: 10,
    })
);

// Cache images
registerRoute(
    /\.(?:png|jpg|jpeg|svg|gif|webp)$/i,
    new CacheFirst({
        cacheName: 'images-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            }),
        ],
    })
);

// Cache CSS files
registerRoute(
    /\.css$/i,
    new StaleWhileRevalidate({
        cacheName: 'css-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 20,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            }),
        ],
    })
);

// Cache JS files
registerRoute(
    /\.js$/i,
    new StaleWhileRevalidate({
        cacheName: 'js-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 30,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            }),
        ],
    })
);

// Offline fallback
self.addEventListener('fetch', (event) => {
    if (event.request.mode === 'navigate') {
        event.respondWith(
            fetch(event.request).catch(() => {
                return caches.match('/index.html');
            })
        );
    }
});

// Background Sync - Sync pending mutations when connection is restored
self.addEventListener('sync', (event: any) => {
    console.log('🔄 Background sync event:', event.tag);

    if (event.tag === 'sync-mutations') {
        event.waitUntil(syncPendingMutations());
    }
});

// Periodic Background Sync - Sync data periodically (every 5 minutes)
self.addEventListener('periodicsync', (event: any) => {
    console.log('⏰ Periodic sync event:', event.tag);

    if (event.tag === 'periodic-sync') {
        event.waitUntil(periodicDataSync());
    }
});

// Helper function to sync pending mutations
async function syncPendingMutations() {
    try {
        console.log('📤 Syncing pending mutations...');

        // Send message to all clients to trigger sync
        const clients = await self.clients.matchAll();
        clients.forEach(client => {
            client.postMessage({
                type: 'SYNC_QUEUE',
                timestamp: Date.now()
            });
        });

        console.log('✅ Sync message sent to clients');
    } catch (error) {
        console.error('❌ Background sync failed:', error);
        throw error;
    }
}

// Helper function for periodic sync
async function periodicDataSync() {
    try {
        console.log('🔄 Periodic data sync...');

        // Send message to all clients to trigger periodic sync
        const clients = await self.clients.matchAll();
        clients.forEach(client => {
            client.postMessage({
                type: 'PERIODIC_SYNC',
                timestamp: Date.now()
            });
        });

        console.log('✅ Periodic sync message sent to clients');
    } catch (error) {
        console.error('❌ Periodic sync failed:', error);
    }
}

// Skip waiting and claim clients
self.addEventListener('install', (event) => {
    console.log('📦 Service worker installing...');
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    console.log('✅ Service worker activated');
    event.waitUntil(self.clients.claim());
});

// Listen for messages from clients
self.addEventListener('message', (event) => {
    console.log('📨 Message received:', event.data);

    if (event.data?.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
